allow-branch = ["main"]
sign-commit = false
sign-tag = false
push-remote = "origin"
tag-prefix = "v"
tag-name = "v{{version}}"
pre-release-commit-message = "release: v{{version}}"
publish = true
push = true
tag = true
